services:
  test-service:
    container_name: my-container
    image: myfirstdockerimage
    command:
      - bash
      - -c
      - |
        echo "container starting"
        apt update
        apt install -y htop bmon vim
        tail -f /dev/null
